export const querySuggestions = [
  "What's the distance between Earth and the Moon?",
  "What are some unconventional home workout routines?",
  "Is there life on Mars?",
  "What is the speed of light?",
  "Can I improve my memory without medication?",
  "What's the psychology behind color preference in marketing?",
  "Is it possible to learn multiple languages simultaneously?",
  "How can I grow taller as an adult?",
  "Explain quantum computing like I'm five",
  "What are some sustainable fashion brands?",
  "What's the connection between music and mental health?",
  "Can meditation really reduce stress and anxiety?",
  "Are there any DIY tricks for cleaning oven stains?",
  "How to make a good cup of coffee?",
  "How do I make my own natural sunscreen?",
  "How do I train for a marathon without joining a gym?",
  "What are some responsible travel tips?",
  "How does a solar eclipse occur?",
  "Do we burn calories while sleeping?",
  "What are the best books to improve coding skills?",
  "How can I improve my public speaking anxiety?",
  "Can you recommend a good online course for digital art?",
  "How do plants communicate with each other?",
  "Can you explain the concept of time dilation in special relativity?",
  "What are some tips for improving indoor air quality?",
  "What are some vegan-friendly sources of protein?",
  "How do I organize a small closet efficiently?",
  "What is the life cycle of a butterfly?",
  "Alternatives to an alarm clock",
  "How to make a good first impression?",
  "Are there any apps that can improve my sleep quality?",
  "What's the difference between mindfulness and meditation?",
  "Can practicing gratitude increase happiness?",
  "How do I troubleshoot a slow internet connection?",
  'What is the origin of the phrase "break a leg" in theater?',
  "How can I improve my golf swing without a coach?",
  "Can you recommend a good podcast on personal finance?",
  "The history of the internet",
  "What's the best way to care for aloe vera plant?",
  "How does the brain create new memories?",
  "Can meditation help with anxiety?",
  "What are some eco-friendly alternatives to plastic wrap?",
  "How do I maintain a healthy work-life balance?",
  "What's the difference between a vegan and vegetarian diet?",
  "Can listening to classical music help improve concentration?",
  "How can I lose weight without exercising?",
  "What's the significance of the Mayan calendar?",
  "Can you explain the science behind dreams?",
  "How do I build a successful online community?",
  "What are some low-carb dinner options for vegetarians?",
  "How do you properly care for a pet hamster?",
  "Is it possible to grow crops in space?",
  "How does the human body process caffeine?",
  "Are there any benefits of taking cold showers first thing in the morning?",
  "What are some creative ways to use old books?",
  "Can you recommend a good online course for learning photography?",
  "How do I manage stress during a busy work schedule?",
  "What's the history behind the Olympic Games?",
  "How does exercise affect mental health?",
  "What are some healthy breakfast options on-the-go?",
  "Are there any apps to track your daily water intake?",
  "How do I start a vegetable garden in my small balcony?",
  "Can you explain the concept of a black hole?",
  "How can I improve my typing speed without lessons?",
  "How do plants respond to different temperatures?",
  "Can you recommend a good podcast series on artificial intelligence?",
  "What's the difference between a comet and an asteroid?",
  "Is it possible to train for a marathon without running long distances in the beginning?",
  "What are some eco-friendly alternatives to plastic containers?",
  "Can you suggest a good meditation technique for beginners?",
  "How can I improve my public speaking without fear?",
  "What's the science behind laughter and its health benefits?",
  "How to make a mobile app?",
  "Tips for a Healthier Lifestyle",
  "Can you recommend a good online platform to learn graphic design?",
  "How do I maintain good posture while working from home?",
  "Are there any apps for tracking daily exercise routines?",
  "What's the difference between a power nap and a regular sleep?",
  "How can I make my own natural insect repellent?",
  "Can you explain the concept of blockchain technology?",
  "What are the benefits of learning a new language?",
  "How do I stay motivated to learn a new skill?",
  "What are some tips for reducing screen time before bed?",
  "Are there any apps to help with time management?",
  "What's the best way to store fresh produce at home?",
  "Can you recommend a good online course for learning Spanish?",
  "How do I start a small business?",
  "Is it possible to grow vegetables in a small apartment without a balcony?",
  "How can I improve my singing voice at home?",
  "What are the health benefits of yoga?",
  "How to start a successful blog",
  "What's the difference between a crocodile and an alligator?",
  "Can you explain the concept of virtual reality technology?",
  "What are some tips for dealing with a difficult team member at work?",
  "Are there any apps to help learn new programming languages?",
  "List of healthy snacks for work",
  "Writing a resume that stands out",
  "Elaborate on the concept of the butterfly effect",
  "Getting started with investing in the stock market",
  "How to make a good first impression in a job interview",
];

export function getRandomQuerySuggestion() {
  return querySuggestions[Math.floor(Math.random() * querySuggestions.length)];
}
