#!/usr/bin/env sh
npm install --no-save @biomejs/biome && npx @biomejs/biome check --write --staged --no-errors-on-unmatched && git diff --name-only --cached | while read -r file; do [ -f "$file" ] && git add "$file"; done
