name: Check Docker Container
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  docker:
    name: Check Docker Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker-compose -f docker-compose.production.yml up -d
      - name: Check if main page is available
        run: until curl -s -o /dev/null -w "%{http_code}" localhost:7860 | grep 200; do sleep 1; done
      - run: docker-compose -f docker-compose.production.yml down
