name: Deploy to Hugging Face

on:
  workflow_dispatch:

jobs:
  sync-to-hf:
    name: Sync to Hugging Face Spaces
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: JacobLinCool/huggingface-sync@60850d5a74ea004fc094f77c960c2c8bd9a0f9d1 # v1.3.1
        with:
          github: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ vars.HF_SPACE_OWNER }}
          space: ${{ vars.HF_SPACE_NAME }}
          token: ${{ secrets.HF_TOKEN }}
          configuration: ".github/hf-space-config.yml"
