on:
  workflow_call:
jobs:
  check-code-quality:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci --ignore-scripts
      - run: npm test
      - run: npm run lint
  check-docker-container:
    needs: [check-code-quality]
    name: Check Docker Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: docker compose -f docker-compose.production.yml up -d
      - name: Check if main page is available
        run: until curl -s -o /dev/null -w "%{http_code}" localhost:7860 | grep 200; do sleep 1; done
        timeout-minutes: 1
      - run: docker compose -f docker-compose.production.yml down
